---
title: "Graphics with ggplot2"
author: "Leslie"
date: "March 12, 2018"
output: html_document
---
## Learning ggplot2

```{r, echo = FALSE}
library(tidyverse)
library(ggthemes)
```

```{r}
mpg
```

```{r}
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point(alpha = 0.4)
```

```{r}
ggplot(mpg, aes(x = displ, y = hwy, color = class)) +
  geom_point()
```

Make a scatterplot of `hwy` vs `cty` with different sized points representing each `class` and differetn colors for each `fl`

```{r}
ggplot(mpg, aes(x = cty, y = hwy, color = fl, size = class)) +
  geom_point()
```

```{r}
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point(alpha = 0.4, color = "purple")
```

```{r}
ggplot(mpg, aes(x = displ, y = hwy, color = class)) +
  geom_point() +
  facet_wrap( ~ manufacturer, ncol = 5) +
  theme_bw()
```

```{r}
ggplot(mpg, aes(x = drv, y = hwy)) +
  geom_boxplot()
```

```{r}
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point() +
  geom_smooth(method = "lm") + 
  theme_bw() +
  labs(title = "Relationship between engine size and highway mileage (mpg)", 
       x = "Engine size (liters displaced)",
       y = "Highway mileage (mpg)") +
  theme(text = element_text(size = 16))
```

